name: cloudsmith_release

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  analyze:
    uses: killbill/gh-actions-shared/.github/workflows/cloudsmith_release.yml@maint-for-0-24-x
    with:
      group_id: 'org.kill-bill.billing.plugin.java'
      artifact_id: 'adyen-plugin'
